name: PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build extension
      run: npm run build

  version-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check version labels
      uses: actions/github-script@v7
      with:
        script: |
          const labels = context.payload.pull_request.labels.map(label => label.name);
          const versionLabels = labels.filter(label => ['patch', 'minor', 'major'].includes(label));
          
          if (versionLabels.length === 0) {
            core.setFailed('❌ Please add a version label (patch, minor, or major) to this PR');
          } else if (versionLabels.length > 1) {
            core.setFailed('❌ Please add only one version label (patch, minor, or major) to this PR');
          } else {
            core.info(`✅ Version label found: ${versionLabels[0]}`);
          }