name: Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build extension
      run: npm run build

    - name: Get version from package.json
      id: version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=v$VERSION" >> $GITHUB_OUTPUT
        echo "Current version: $VERSION"

    - name: Check if tag already exists
      id: check-tag
      run: |
        if git rev-parse "v${{ steps.version.outputs.version }}" >/dev/null 2>&1; then
          echo "tag-exists=true" >> $GITHUB_OUTPUT
          echo "Tag v${{ steps.version.outputs.version }} already exists"
        else
          echo "tag-exists=false" >> $GITHUB_OUTPUT
          echo "Tag v${{ steps.version.outputs.version }} does not exist"
        fi

    - name: Create and push tag
      if: steps.check-tag.outputs.tag-exists == 'false'
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git tag ${{ steps.version.outputs.tag }}
        git push origin ${{ steps.version.outputs.tag }}

    - name: Create extension archive
      if: steps.check-tag.outputs.tag-exists == 'false'
      run: |
        cd dist
        zip -r ../extension-${{ steps.version.outputs.tag }}.zip .
        cd ..

    - name: Create Release
      if: steps.check-tag.outputs.tag-exists == 'false'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.tag }}
        name: Extension ${{ steps.version.outputs.tag }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: extension-${{ steps.version.outputs.tag }}.zip
        body: |
          🚀 **Browser Extension Release ${{ steps.version.outputs.tag }}**
          
          ## Installation
          1. Download the `extension-${{ steps.version.outputs.tag }}.zip` file below
          2. Extract the contents to a folder
          3. Open your browser's extension management page
          4. Enable "Developer mode"
          5. Click "Load unpacked" and select the extracted folder
          
          ## What's Changed
          This release includes all changes merged since the previous version.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Skip release (tag exists)
      if: steps.check-tag.outputs.tag-exists == 'true'
      run: |
        echo "⚠️ Tag ${{ steps.version.outputs.tag }} already exists. Skipping release creation."
